version: "3.8"
services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: "always"
    entrypoint: ["/app/main"]

  lb:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: "always"
    ports:
      - "8080:8080"
    depends_on:
      - account