// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
  owner,
  balance,
  currency
) VALUES (
  $1, $2, $3
)
`

func (q *Queries) CreateAccount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createAccount)
	return err
}
