version: "3.9"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "14222:4222"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 512M
        reservations:
          memory: 50M
    command: "--cluster_name NATS --cluster nats://nats:6222 --http_port 8222"
#    networks: [ "nats" ]

  nats2:
    image: nats
    ports:
      - "24222:4222"
      - "28222:8222"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 512M
        reservations:
          memory: 50M
    command: "--cluster_name NATS --cluster nats://nats2:6222 --http_port 8222 --routes=nats://nats:6222"
#    networks: [ "nats" ]
    depends_on: [ "nats" ]

  nats3:
    image: nats
    ports:
      - "34222:4222"
      - "38222:8222"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 512M
        reservations:
          memory: 50M
    command: "--cluster_name NATS --cluster nats://nats3:6222 --http_port 8222 --routes=nats://nats:6222"
#    networks: [ "nats" ]
    depends_on: [ "nats" ]

#networks:
#  nats:
#    name: nats


#  nats1:
#    image: nats
#    command:
#      - "--debug"
#      - "--name=nats1"
#      - "--cluster_name=c1"
#      - "--cluster=nats://nats1:6222"
#      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
#      - "--http_port=8222"
##      - "--js"
#
#  nats2:
#    image: nats
#    command:
#      - "--debug"
#      - "--name=nats2"
#      - "--cluster_name=c1"
#      - "--cluster=nats://nats2:6222"
#      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
#      - "--http_port=8222"
##      - "--js"
#
#  nats3:
#    image: nats
#    command:
#      - "--debug"
#      - "--name=nats3"
#      - "--cluster_name=c1"
#      - "--cluster=nats://nats3:6222"
#      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
#      - "--http_port=8222"
##      - "--js"
