version: "3.8"

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - 17474:7474
      - 17687:7687
    volumes:
      - ./data:/data
    environment:
      - "publish=7474:7474"
      - "publish=7687:7687"
