mockgenfriend:
	mockgen -destination service/mock/friend/friend_mock.go -package mockfriendsvc -source service/friend.go Friender

mockgenuser:
	mockgen -destination service/mock/user/user_mock.go -package mockusersvc -source service/user.go UserManager
