version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: "always"
    entrypoint: ["/app/main"]

  lb:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    restart: "always"
    ports:
      - "80:80"
    depends_on:
      - api
