// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgServiceClient interface {
	SendToUser(ctx context.Context, opts ...grpc.CallOption) (MsgService_SendToUserClient, error)
}

type msgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServiceClient(cc grpc.ClientConnInterface) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) SendToUser(ctx context.Context, opts ...grpc.CallOption) (MsgService_SendToUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &MsgService_ServiceDesc.Streams[0], "/MsgService/SendToUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &msgServiceSendToUserClient{stream}
	return x, nil
}

type MsgService_SendToUserClient interface {
	Send(*SendUserRequest) error
	Recv() (*SendUserResponse, error)
	grpc.ClientStream
}

type msgServiceSendToUserClient struct {
	grpc.ClientStream
}

func (x *msgServiceSendToUserClient) Send(m *SendUserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *msgServiceSendToUserClient) Recv() (*SendUserResponse, error) {
	m := new(SendUserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MsgServiceServer is the server API for MsgService service.
// All implementations must embed UnimplementedMsgServiceServer
// for forward compatibility
type MsgServiceServer interface {
	SendToUser(MsgService_SendToUserServer) error
	mustEmbedUnimplementedMsgServiceServer()
}

// UnimplementedMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (UnimplementedMsgServiceServer) SendToUser(MsgService_SendToUserServer) error {
	return status.Errorf(codes.Unimplemented, "method SendToUser not implemented")
}
func (UnimplementedMsgServiceServer) mustEmbedUnimplementedMsgServiceServer() {}

// UnsafeMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServiceServer will
// result in compilation errors.
type UnsafeMsgServiceServer interface {
	mustEmbedUnimplementedMsgServiceServer()
}

func RegisterMsgServiceServer(s grpc.ServiceRegistrar, srv MsgServiceServer) {
	s.RegisterService(&MsgService_ServiceDesc, srv)
}

func _MsgService_SendToUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MsgServiceServer).SendToUser(&msgServiceSendToUserServer{stream})
}

type MsgService_SendToUserServer interface {
	Send(*SendUserResponse) error
	Recv() (*SendUserRequest, error)
	grpc.ServerStream
}

type msgServiceSendToUserServer struct {
	grpc.ServerStream
}

func (x *msgServiceSendToUserServer) Send(m *SendUserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *msgServiceSendToUserServer) Recv() (*SendUserRequest, error) {
	m := new(SendUserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MsgService_ServiceDesc is the grpc.ServiceDesc for MsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendToUser",
			Handler:       _MsgService_SendToUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "msg_service.proto",
}
