global:
  scrape_interval: 15s # 수집주기 15초

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['promex:9090']

  - job_name: 'mysql_exporter'
    static_configs:
    - targets: ['mysqlexporter:9104']
#    params:
#      collect[]:
#      - 'collect.info_schema.processlist'