version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test